#pragma once

/* Copyright (C) 2019-2020 Mono Wireless Inc. All Rights Reserved.
 * 
 * The twesettings library is dual-licensed under MW-SLA and MW-OSSLA terms.
 * - MW-SLA-1J,1E or later (MONO WIRELESS SOFTWARE LICENSE AGREEMENT).
 * - MW-OSSLA-1J,1E or later (MONO WIRELESS OPEN SOURCE SOFTWARE LICENSE AGREEMENT). */

#define TWEINTRCT_KEY_UP 0x18A
#define TWEINTRCT_KEY_DOWN 0x18B
#define TWEINTRCT_KEY_RIGHT 0x18C
#define TWEINTRCT_KEY_LEFT 0x18D

#define TWEINTRCT_KEY_BUTTON_A 0x290
#define TWEINTRCT_KEY_BUTTON_B 0x291
#define TWEINTRCT_KEY_BUTTON_C 0x292
#define TWEINTRCT_KEY_BUTTON_A_LONG 0x298
#define TWEINTRCT_KEY_BUTTON_B_LONG 0x299
#define TWEINTRCT_KEY_BUTTON_C_LONG 0x29A

#define TWEINTRCT_KEY_ENTER 0x0D
#define TWEINTRCT_KEY_BS 0x08
#define TWEINTRCT_KEY_SPACE 0x20
#define TWEINTRCT_KEY_ESC 0x1B
