/* Copyright (C) 2019-2020 Mono Wireless Inc. All Rights Reserved.
 * Released under MW-OSSLA-1J,1E (MONO WIRELESS OPEN SOURCE SOFTWARE LICENSE AGREEMENT). */

#include <mwm5.h>

MWM5_DECL_APP_NAME("TWELITE STAGE");
MWM5_DECL_APP_VERSION_MAIN(0);
MWM5_DECL_APP_VERSION_SUB(9);
MWM5_DECL_APP_VERSION_VAR(11);